name: Node Build

on: [push]

jobs:
  mainbuild:
    runs-on: ubuntu-latest # Spécifie que ce job doit s'exécuter sur Ubuntu

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest] # Spécifie Ubuntu dans la matrice

    steps:
      - uses: actions/checkout@v1
      - name: Run node.js on latest ubuntu.
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM and build.
        run: |
          npm ci
          npm run build
