name: Node Build

on: [push]

jobs:
  mainbuild:
    runs-on: ${{ matrix.os }}

    strategy: # Indentation fixée ici
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Run node.js on latest ubuntu.
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM and build.
        run: |
          npm ci
          npm run build
